In [1]:
import numpy as np

a = np.random.randn(3, 4)

In [21]:
100 * 0.5**3

12.5

In [6]:
a = np.random.randn(3, 4, 5)
b = np.random.randn(3, 4)
c = np.random.randn(4, 5)
print (a * c)
print (a * b)

[[[-0.95269343  0.26660853 -0.33847914 -0.35055174  0.68925515]
  [ 0.12350817 -0.23915116  1.59184456  0.2770105   0.35820494]
  [-0.50129027  0.17760822 -0.63869544  0.00733474  0.00820706]
  [-0.25366861 -0.64081251 -0.18390524  0.4356048   0.23230744]]

 [[-2.03108764  0.33478424 -0.02154963 -0.15173198 -0.2129348 ]
  [-0.03408546 -0.32362662 -0.8339189  -0.95471929 -0.18627938]
  [-0.3218044  -0.01066609 -0.07162795 -0.54283122  0.05672988]
  [ 0.37276525 -3.05448565  0.18096267  0.64777892  0.58203416]]

 [[ 0.35602399 -0.26397614 -0.49222952  0.7800755   0.25419519]
  [ 0.28267296  0.13734074 -2.3815375   0.26231365  0.24096975]
  [-1.25126212  0.04318167  0.20524818  0.12749037 -0.02686925]
  [-1.29228822 -0.13695635 -0.00847936  0.91345373  1.42146256]]]


ValueError: operands could not be broadcast together with shapes (3,4,5) (3,4) 

In [22]:
np.zeros([3, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
np.linalg.norm(a[0], b[0])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
class GameState(object):
    def __init__(self):
        self.level = 0
        self.lives = 0

In [30]:
state = GameState()
state.level += 1
state.lives -= 1

In [31]:
pwd

u'/jupyter/tomoaki/Indicator Analysis'

In [34]:
import pickle

state_path = "/jupyter/tomoaki/Indicator Analysis/trail.bin"
with open(state_path, "wb") as f:
    pickle.dump(state, f)

In [36]:
with open(state_path, "rb") as f:
    state_after = pickle.load(f)
print (state_after.__dict__)

{'lives': -1, 'level': 1}


In [42]:
from time import localtime, strftime, time
a = localtime(time())
print (a)
time_format = '%Y-%m-%d %H:%M:%S'
print (strftime(time_format, a))

time.struct_time(tm_year=2016, tm_mon=7, tm_mday=4, tm_hour=22, tm_min=19, tm_sec=33, tm_wday=0, tm_yday=186, tm_isdst=0)
2016-07-04 22:19:33


In [46]:
from time import mktime, strptime
b= strftime(time_format, a)
a = strptime(b, time_format)
print(a)
utc_now = mktime(a)
print (utc_now)

time.struct_time(tm_year=2016, tm_mon=7, tm_mday=4, tm_hour=22, tm_min=19, tm_sec=33, tm_wday=0, tm_yday=186, tm_isdst=-1)
1467670773.0


In [49]:
import datetime

arrival_nyc = '2014-05-01 23:33:24'
nyc_dt_naive = datetime.datetime.strptime(arrival_nyc, time_format)

In [50]:
print (nyc_dt_naive)

2014-05-01 23:33:24


In [51]:
import pytz

eastern = pytz.timezone('US/Eastern')
nyc_dt = eastern.localize(nyc_dt_naive)
utc_dt = pytz.utc.normalize(nyc_dt.astimezone(pytz.utc))

In [52]:
print (nyc_dt)
print (utc_dt)

2014-05-01 23:33:24-04:00
2014-05-02 03:33:24+00:00


In [54]:
jp_dt = pytz.utc.normalize(utc_dt.astimezone(japan))

NameError: name 'japan' is not defined

In [86]:
r2 = BoundOhms(10)
r2.ohms  = 1
r2.ohms = 0

ValueError: 0.000000 must be above 0

In [87]:
r = BoundOhms(-1)

ValueError: -1.000000 must be above 0

In [55]:
import tensorflow as tf

In [58]:
a = tf.placeholder(tf.float32, [10, 10])
a = tf.reshape(a, [10, 1, 10])
print (a.get_shape().as_list())

[10, 1, 10]


In [60]:
b = tf.unpack(a)
print (b[0].get_shape().as_list())

[1, 10]


In [93]:
a = tf.zeros([0, 0])

In [94]:
a

<tf.Tensor 'zeros_2:0' shape=(0, 0) dtype=float32>

In [95]:
a = tf.zeros([2, 3])

In [96]:
a

<tf.Tensor 'zeros_3:0' shape=(2, 3) dtype=float32>

In [97]:
a = [(i, j) for i in xrange(10) for j in xrange(5)]

In [8]:
import tensorflow as tf

weights = tf.get_variable("weights", [2, 3],
        initializer=tf.random_normal_initializer())

In [9]:
weights.op.name

u'weights'

In [10]:
a = weights
print a.op.name

weights


In [12]:
with tf.variable_scope("my_scope"):
    b = weights

In [13]:
b.op.name

u'weights'

In [26]:
import numpy as np

a = np.arange(11)
np.array_split(a, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]

In [29]:
a = np.random.randn(10)
c = np.argsort(a)
print (a[c])


[-1.21698653 -1.20927672 -0.79435896 -0.4872107   0.09810145  0.21398059
  0.86076722  0.8914216   0.94247654  2.70303004]


In [30]:
a = np.random.randn(1, 10)
a.ravel()

array([ 1.41820027, -1.54021233,  1.79036774, -0.23048187, -1.25125616,
       -0.83287221, -1.54704591,  0.05177696,  1.31969452,  1.35602896])

In [8]:
import tensorflow